'
' Copyright (C) 2019 - 2020 Rabobank Nederland
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'         http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml

caption Argos Server oauth2 authorization flow for azure

skinparam shadowing<<with_shadow>> true
skinparam backgroundColor #SeaShell

actor personalAccount
participant browser
participant "argos service" as argos
participant "external authorization service" as auth
participant "personalAccount profile service (external resource server)" as up
database "database"

personalAccount -> browser: signup / signin

browser -> argos: get oauth2/authorize/azure
argos --> browser: redirect to authorization service

browser -> auth: get /oauth2/v2.0/authorize
auth --> browser: login page
browser --> personalAccount: show login page

personalAccount -> browser: enter credentials
browser -> auth: post credentials
auth --> browser: personalAccount consent page
browser --> personalAccount: show personalAccount consent page

personalAccount -> browser: personalAccount agrees
browser -> auth: post agree
auth --> browser: redirect to argos service /oauth2/callback/azure
browser -> argos: get /oauth2/callback/azure
argos -> auth: post /oauth2/v2.0/token
auth --> argos: returns token
argos -> up: get userprofile
up --> argos: returns userprofile
argos -> database: store / update personalAccount profile
argos --> browser: redirect to argos frontend
browser --> personalAccount: show argos frontend
@enduml