'
' Copyright (C) 2019 - 2020 Rabobank Nederland
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'         http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml

caption MetaBlock for Layouts and Links

skinparam shadowing<<with_shadow>> true
skinparam backgroundColor #SeaShell

class MetaBlock {  
}

class Signature {
    signature
}

class Key {
}

class Account {
}

class Signable {
}

class Layout {
}

class Link {
}

MetaBlock "1" -left-> "1..*" Signature
MetaBlock "1" -right-> "1..*" Signable
Signable <|-- Layout
Signable <|-- Link
Signature "1" -down-> "1" Key
Account "1" -right- "1" Key

@enduml
